### ISSUE TITLE
Create Helm Charts

### ISSUE THREAD

**Issue by quentinguidee** [vertex-center/vertex#133]
### Request

Create Helm Charts to run a cluster of vertex services easily in Kubernetes with Terraform/Tofu

### Why is this needed?

- To start Vertex easily

### Todo

- [x] Init helm chart
- [x] Create Docker images for each apps
- [x] Create the subcharts
- [x] Host the charts

**Comment by quentinguidee** [comment]
Repository: https://github.com/vertex-center/helm-charts

**Comment by quentinguidee** [comment]
Done with https://github.com/vertex-center/charts and https://github.com/vertex-center/tf
